### PR TITLE
Support null-safety

### PR DESCRIPTION
**Pull request by adamwalzer**
Minor updates to support dart version >=2.12 including null-safety

### CODE REVIEW

**Comment by skipness** [comment]
Thanks for the PR! I will take a look on weekend

**Comment by adamwalzer** [comment]
Thanks. Hopefully this helps. I really appreciate you maintaining this repo. I likely won't be able to apply any necessary fixes until next week.

**Comment by skipness** [comment]
@adamwalzer I doesn't have time to review this PR yet so please wait , I am sorry.

**Comment by alejandrogiubel** [comment]
Hi I need these update. All my app is now in null safety. It is an amazing plugin.

**Comment by joo** [comment]
Hi I need these update. All my app is now in null safety.

**Comment by skipness** [comment]
@adamwalzer Hi, sorry for super super late response
The changes looks good in general, but I am thinking about if we could make all of the api become null safe instead of some of them, for example `compressToUTF16` will return an empty string now instead of `null`.
How do you think?

**Comment by adamwalzer** [comment]
I agree that that makes sense. The reason why I didn't do that is that I didn't want to change what the functions return because I didn't know if people would be relying on how they currently work. That could be a breaking change. If we want to do that, we might have to make that a major version change.

**Comment by skipness** [comment]
Yes you are right! I will accept this PR. Would you like to make another PR for fully null safety?

**Comment by adamwalzer** [comment]
Will do. I likely won't get to this right away though.

**Comment by skipness** [comment]
That's ok, thank you!

**Pull request merged**
